In [1]:
import pandas as pd
import os
from tqdm import tqdm

In [2]:
df_0030 = pd.read_csv("../datasets/schaefcomb_Wang2023Simple_ds000030.tsv", sep = "\t")

df_4302 = pd.read_csv("../datasets/schaefcomb_wang2023SimpleCorrMatrix_ds004302.tsv", sep = "\t")

df_cobre = pd.read_csv("../datasets/schaefcomb_wang2023SimpleCorrMatrix_cobre.tsv", sep = "\t")

/tmp/ipykernel_778454/508707093.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_cobre = pd.read_csv("../datasets/schaefcomb_wang2023SimpleGSRCorrMatrix_cobre.tsv", sep = "\t")

In [3]:
df_abide1 = pd.read_csv("../datasets/schaefcomb_Wang2023Simple_abide1.tsv", sep = "\t")

df_abide2 = pd.read_csv("../datasets/schaefcomb_Wang2023Simple_abide2.tsv", sep = "\t")

In [4]:
# Création de la colonne diagnosis
df_4302["diagnosis"] = df_4302["group"].map({
    "HC": "CONTROL",
    "AVH-": "SCHZ",
    "AVH+": "SCHZ",
})

df_4302["diagnosis"] = df_4302["diagnosis"].fillna("UNKNOWN")

# Renommer les valeurs de gender
df_4302["gender"] = df_4302["gender"].replace({
    "male": "M",
    "female": "F",
})

# Replacer la colonne diagnosis juste après "group"
cols = list(df_4302.columns)
group_idx = cols.index("group")
# retirer puis réinsérer à la bonne position
cols.insert(group_idx + 1, cols.pop(cols.index("diagnosis")))
df_4302 = df_4302[cols]

In [5]:
df_4302

,participant_id,group,diagnosis,age,gender,corr_1_2,corr_1_3,corr_1_4,corr_1_5,corr_1_6,...,corr_430_431,corr_430_432,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434
0,sub-21,HC,CONTROL,42,M,0.260057,0.261104,-0.089561,-0.455227,-0.132276,...,NaN,-0.067477,0.255018,0.630073,NaN,NaN,NaN,0.129936,0.042653,0.272183
1,sub-10,HC,CONTROL,36,F,0.457691,0.132095,-0.037439,NaN,NaN,...,NaN,0.404580,0.328437,0.777075,NaN,NaN,NaN,0.117329,0.305994,0.348293
2,sub-29,AVH-,SCHZ,38,M,0.108464,0.382382,0.011199,0.113299,0.132078,...,NaN,0.154893,0.330102,0.639154,NaN,NaN,NaN,0.187120,0.059177,0.296410
3,sub-55,AVH+,SCHZ,44,M,-0.300822,0.181359,-0.085185,0.385769,0.079273,...,NaN,0.112297,0.307445,0.471354,NaN,NaN,NaN,0.259371,0.152311,0.445420
4,sub-13,HC,CONTROL,21,M,0.506121,0.067694,0.095354,NaN,NaN,...,NaN,0.440765,0.539905,0.742611,NaN,NaN,NaN,0.345999,0.425908,0.459046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,sub-02,HC,CONTROL,36,M,0.376694,-0.251911,0.110173,0.013275,-0.197859,...,NaN,-0.056809,-0.008535,0.600761,NaN,NaN,NaN,-0.075790,-0.094518,-0.174423
67,sub-23,HC,CONTROL,33,M,0.074220,NaN,-0.039888,NaN,NaN,...,NaN,0.166109,0.307369,NaN,NaN,NaN,NaN,-0.000363,NaN,NaN
68,sub-59,AVH+,SCHZ,25,M,-0.022304,NaN,0.268348,NaN,NaN,...,NaN,-0.060189,0.115147,0.795746,NaN,NaN,NaN,0.061766,-0.034630,0.189987
69,sub-66,AVH+,SCHZ,44,M,0.202535,0.372287,0.261661,0.062653,0.235857,...,NaN,-0.014756,0.190212,0.633174,NaN,NaN,NaN,-0.156721,-0.038832,0.202676
70,sub-48,AVH-,SCHZ,47,F,0.128775,0.475732,-0.106950,NaN,-0.424029,...,NaN,0.039967,0.195661,0.422963,NaN,NaN,NaN,0.144132,-0.102233,-0.045967

In [6]:
# Retirer group dans df_4302
df_4302 = df_4302.drop(columns=["group"])

# Ajouter la colonne site_id avant la concaténation
df_0030.loc[:, "site_id"] = "ds000030"
df_4302.loc[:, "site_id"] = "ds004302"

# Concaténer verticalement
df_open = pd.concat([df_0030, df_4302], ignore_index=True)

# Replacer site_id juste après diagnosis
cols = list(df_open.columns)
diag_idx = cols.index("diagnosis")
cols.insert(diag_idx + 1, cols.pop(cols.index("site_id")))
df_open = df_open[cols]

In [7]:
df_abide1

,participant_id,site,diagnosis,age,gender,corr_1_2,corr_1_3,corr_1_4,corr_1_5,corr_1_6,...,corr_430_431,corr_430_432,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434
0,sub-0051327,MAX_MUN,Autism,58.0000,Male,0.068060,0.109962,0.244001,-0.075871,0.159535,...,NaN,0.160957,NaN,0.474153,NaN,NaN,NaN,NaN,0.129837,NaN
1,sub-0051350,MAX_MUN,Autism,11.0000,Male,0.422009,0.644503,0.585167,0.054659,0.486628,...,NaN,0.395008,0.725306,0.796774,NaN,NaN,NaN,0.382126,0.403585,0.717718
2,sub-0050442,USM,Control,26.8528,Male,0.364504,0.296274,0.333017,0.195344,0.283931,...,NaN,0.158716,0.310589,0.373891,NaN,NaN,NaN,0.327270,0.127001,0.156340
3,sub-0050818,KKI,Control,11.7900,Male,0.454565,NaN,0.151757,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sub-0050435,USM,Control,16.1040,Male,0.315617,0.455101,0.377455,0.280111,0.371497,...,NaN,0.456259,0.593961,0.883734,NaN,NaN,NaN,0.372818,0.448132,0.594389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,sub-0050958,NYU,Autism,10.2300,Female,0.407991,0.714125,0.468836,0.260115,0.504558,...,NaN,0.421856,0.704278,0.886329,NaN,NaN,NaN,0.650371,0.338237,0.617674
885,sub-0050502,USM,Autism,32.9582,Male,0.449186,0.459701,0.420416,0.338380,0.145211,...,NaN,0.270311,0.585654,0.699349,NaN,NaN,NaN,0.347197,0.250888,0.706590
886,sub-0050048,PITT,Control,11.8100,Male,0.203365,0.440124,0.215439,0.296243,0.283935,...,NaN,0.430165,0.618337,0.794788,NaN,NaN,NaN,0.558751,0.521876,0.611008
887,sub-0050145,OHSU,Autism,10.7500,Male,0.268654,0.394133,0.091558,0.083394,0.144676,...,NaN,0.537695,0.699533,0.798897,NaN,NaN,NaN,0.658033,0.536027,0.772036
888,sub-0050132,OLIN,Autism,16.0000,Male,0.518398,0.413630,0.397955,0.145128,0.149429,...,NaN,0.282904,0.722972,0.709908,NaN,NaN,NaN,0.449350,0.230280,0.714200

In [8]:
df_abide2

,participant_id,session_used,no_run_filename,site,diagnosis,age,gender,corr_1_2,corr_1_3,corr_1_4,...,corr_430_431,corr_430_432,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434
0,sub-30011,ses-1,False,ABIDEII-UCD_1,Autism,12.000000,male,0.150613,0.295193,0.185033,...,NaN,NaN,0.597075,0.676654,NaN,NaN,NaN,NaN,NaN,0.653662
1,sub-29678,ses-1,False,ABIDEII-KUL_3,Autism,18.000000,male,0.461751,0.467274,0.096404,...,NaN,-0.063728,0.001189,0.392803,NaN,NaN,NaN,0.588457,-0.067630,0.241321
2,sub-28894,ses-1,False,ABIDEII-SDSU_1,Control,11.200000,male,0.304191,0.434931,0.073266,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.074034
3,sub-28900,ses-1,False,ABIDEII-SDSU_1,Control,13.000000,male,0.659172,0.420396,0.470115,...,NaN,0.176971,0.386245,0.741179,NaN,NaN,NaN,0.520780,0.139934,0.436217
4,sub-28977,ses-1,False,ABIDEII-OHSU_1,Control,9.000000,female,0.620594,0.621142,0.315675,...,NaN,0.024430,0.419685,0.710537,NaN,NaN,NaN,0.036617,-0.075687,0.663549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,sub-28837,ses-1,False,ABIDEII-GU_1,Control,11.758904,male,0.441081,0.399933,0.387020,...,NaN,0.102729,0.496377,0.439423,NaN,NaN,NaN,0.205219,0.098855,0.583674
958,sub-28840,ses-1,False,ABIDEII-GU_1,Autism,11.652055,male,0.609567,0.663066,0.514867,...,NaN,-0.091047,0.185786,0.734258,NaN,NaN,NaN,0.574578,-0.044979,0.264622
959,sub-29391,ses-1,True,ABIDEII-KKI_1,Autism,8.013699,male,0.423738,0.354359,0.503601,...,NaN,0.031034,0.700390,0.887639,NaN,NaN,NaN,0.309402,0.103456,0.797907
960,sub-29205,ses-1,False,ABIDEII-NYU_1,Autism,26.620000,male,0.642198,0.651752,0.497581,...,NaN,0.315440,0.408485,0.627991,NaN,NaN,NaN,0.400040,0.114602,0.484904
961,sub-29308,ses-1,True,ABIDEII-KKI_1,Control,11.843836,male,0.420062,0.390432,0.367030,...,NaN,-0.059499,0.359635,0.471426,NaN,NaN,NaN,0.393995,-0.074756,0.412105

In [9]:
df_abide2 = df_abide2.drop(columns=["session_used", "no_run_filename"])

In [10]:
df_abide2 = (
    df_abide2
    .drop(columns=["session_used", "no_run_filename"], errors="ignore")
    .rename(columns={"site": "site_id"})
)

df_abide1 = (
    df_abide1.rename(columns={"site": "site_id"})
)

In [11]:
# Garder uniquement Control ou Patient
df_cobre = df_cobre[df_cobre["group"].isin(["Control", "Patient"])].copy()

# Remplacer les valeurs
df_cobre["group"] = df_cobre["group"].replace({
    "Control": "CONTROL",
    "Patient": "SCHZ"
})

# 3. Convertir age en float
df_cobre["age"] = df_cobre["age"].astype(float)

# 4. Ajouter colonne site
df_cobre["site_id"] = "ds_cobre"

# 5. Ajouter colonne diagnosis
df_cobre["diagnosis"] = df_cobre["group"].copy()

In [12]:
df_cobre

,participant_id,group,age,gender,corr_1_2,corr_1_3,corr_1_4,corr_1_5,corr_1_6,corr_1_7,...,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434,site_id,diagnosis
1,sub-0040025,SCHZ,33.0,M,0.328032,0.589011,0.473182,0.224992,0.398275,0.383038,...,0.843858,0.831421,NaN,NaN,NaN,0.495688,0.425683,0.812936,ds_cobre,SCHZ
2,sub-0040079,SCHZ,26.0,M,0.510712,0.324923,-0.022333,-0.158258,0.118537,-0.248673,...,0.561737,0.519739,NaN,NaN,NaN,0.030595,-0.080179,0.587474,ds_cobre,SCHZ
3,sub-0040062,CONTROL,50.0,M,0.557951,0.541539,0.393446,0.423450,0.689149,-0.074260,...,0.531679,0.621323,NaN,NaN,NaN,0.354909,-0.106240,0.434653,ds_cobre,CONTROL
4,sub-0040110,SCHZ,43.0,M,0.167005,0.705872,-0.094055,0.133829,0.428239,0.094158,...,0.748208,0.747917,NaN,NaN,NaN,-0.103421,0.016269,0.786472,ds_cobre,SCHZ
5,sub-0040097,SCHZ,52.0,F,0.558480,0.508952,0.192424,0.118128,0.276193,0.042147,...,0.664043,0.814652,NaN,NaN,NaN,0.583803,0.190179,0.568703,ds_cobre,SCHZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,sub-0040109,SCHZ,33.0,M,0.509909,0.648256,0.368561,0.269486,0.339154,0.283008,...,0.569751,0.642109,NaN,NaN,NaN,-0.041065,-0.012960,0.331764,ds_cobre,SCHZ
144,sub-0040139,CONTROL,28.0,F,0.201015,0.659998,0.249428,0.447337,0.572041,0.099193,...,0.612552,0.790864,NaN,NaN,NaN,0.020178,-0.087654,0.675409,ds_cobre,CONTROL
145,sub-0040100,SCHZ,35.0,M,0.663684,-0.109535,-0.039656,-0.509296,-0.184351,-0.470632,...,0.879938,0.892022,NaN,NaN,NaN,-0.115466,-0.240822,0.893324,ds_cobre,SCHZ
146,sub-0040000,SCHZ,20.0,F,0.393050,0.256273,0.027250,0.107054,0.458977,0.338626,...,0.583226,0.610135,NaN,NaN,NaN,0.375861,0.268279,0.581998,ds_cobre,SCHZ
147,sub-0040138,CONTROL,28.0,M,0.442539,0.427800,0.226843,0.184435,0.382730,0.451067,...,0.833056,0.871146,NaN,NaN,NaN,0.525229,0.342638,0.823662,ds_cobre,CONTROL

In [13]:
# Concaténer verticalement
df_open_abide1 = pd.concat([df_open, df_abide1], ignore_index=True)

In [14]:
df_open_abide1_cobre = pd.concat([df_open_abide1, df_cobre], ignore_index=True)

In [15]:
df_all = pd.concat([df_open_abide1_cobre, df_abide2], ignore_index=True)

In [16]:
# Normaliser diagnosis
df_all["diagnosis"] = df_all["diagnosis"].replace({
    "Control": "CONTROL",
    "control": "CONTROL"
})

# Normaliser gender
df_all["gender"] = df_all["gender"].replace({
    "Male": "M", "male": "M", "M": "M",
    "Female": "F", "female": "F", "F": "F"
})

In [17]:
df_all[df_all["site_id"] == "ds_cobre"]

,participant_id,diagnosis,site_id,age,gender,corr_1_2,corr_1_3,corr_1_4,corr_1_5,corr_1_6,...,corr_430_432,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434,group
1221,sub-0040025,SCHZ,ds_cobre,33.0,M,0.328032,0.589011,0.473182,0.224992,0.398275,...,0.528081,0.843858,0.831421,NaN,NaN,NaN,0.495688,0.425683,0.812936,SCHZ
1222,sub-0040079,SCHZ,ds_cobre,26.0,M,0.510712,0.324923,-0.022333,-0.158258,0.118537,...,0.157349,0.561737,0.519739,NaN,NaN,NaN,0.030595,-0.080179,0.587474,SCHZ
1223,sub-0040062,CONTROL,ds_cobre,50.0,M,0.557951,0.541539,0.393446,0.423450,0.689149,...,0.137603,0.531679,0.621323,NaN,NaN,NaN,0.354909,-0.106240,0.434653,CONTROL
1224,sub-0040110,SCHZ,ds_cobre,43.0,M,0.167005,0.705872,-0.094055,0.133829,0.428239,...,-0.049243,0.748208,0.747917,NaN,NaN,NaN,-0.103421,0.016269,0.786472,SCHZ
1225,sub-0040097,SCHZ,ds_cobre,52.0,F,0.558480,0.508952,0.192424,0.118128,0.276193,...,0.386021,0.664043,0.814652,NaN,NaN,NaN,0.583803,0.190179,0.568703,SCHZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1362,sub-0040109,SCHZ,ds_cobre,33.0,M,0.509909,0.648256,0.368561,0.269486,0.339154,...,0.001326,0.569751,0.642109,NaN,NaN,NaN,-0.041065,-0.012960,0.331764,SCHZ
1363,sub-0040139,CONTROL,ds_cobre,28.0,F,0.201015,0.659998,0.249428,0.447337,0.572041,...,0.083698,0.612552,0.790864,NaN,NaN,NaN,0.020178,-0.087654,0.675409,CONTROL
1364,sub-0040100,SCHZ,ds_cobre,35.0,M,0.663684,-0.109535,-0.039656,-0.509296,-0.184351,...,-0.054443,0.879938,0.892022,NaN,NaN,NaN,-0.115466,-0.240822,0.893324,SCHZ
1365,sub-0040000,SCHZ,ds_cobre,20.0,F,0.393050,0.256273,0.027250,0.107054,0.458977,...,0.361932,0.583226,0.610135,NaN,NaN,NaN,0.375861,0.268279,0.581998,SCHZ
1366,sub-0040138,CONTROL,ds_cobre,28.0,M,0.442539,0.427800,0.226843,0.184435,0.382730,...,0.475665,0.833056,0.871146,NaN,NaN,NaN,0.525229,0.342638,0.823662,CONTROL

In [18]:
df_all.to_csv("schaefcomb_Wang2023Simple_all.tsv", sep = "\t")